name: Build-and-Deploy-to-Azure-FunctionApp

on:
  push:
    branches:
      - main1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: test
      run: dotnet test
