name: "Code Scanning"

on:
  push:
    branches:
      - main  # Change if you're using a different default branch like 'master'

permissions:
  security-events: write
  pull-requests: read
  contents: write
  statuses: write
  actions: read
  pages: write

jobs:
  codeql:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        # uses: actions/checkout@v4.1.7
        uses: actions/checkout@v3

      - name: Setup .NET Core
        # uses: actions/setup-dotnet@v4.0.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV 

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "csharp"  # Specify the languages you're analyzing (adjust as necessary)

      - name: Build
        run: dotnet build --configuration release
        
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: 'security'
        # continue-on-error: true

      # - name: validate sarif file
      #   run: |
      #     ls -l /home/runner/work/SampleWebApp/results/
      #     # cat /home/runner/work/SampleWebApp/results/csharp.sarif     

      # - name: Upload SARIF file to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: /home/runner/work/SampleWebApp/results/csharp.sarif
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
